In [1]:
import numpy as np
from IPython  import display

In [2]:
a1 = np.array([x for x in range(5)])
a1, type(a1)

(array([0, 1, 2, 3, 4]), numpy.ndarray)

In [3]:
#create array with n-1 numbers
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#create 2D array
#zeros
a3 = np.zeros((2,4))
#ones
a4 = np.ones((2,4))

a3.shape, a4.shape #(rows, columns)

((2, 4), (2, 4))

In [5]:
display.display(a3)
display.display(a4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Create an array of n points between a fixe domain

In [7]:
a5 = np.linspace(0,1,10)
display.display(a5)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### Numpy arrays contain type float elements

In [8]:
type(a5), a5.dtype, a5.shape

(numpy.ndarray, dtype('float64'), (10,))

## Array Dimension

#### For 1D arrays the method a.shape only displays its len:  output  (len,)

In [9]:
display.display(a1)
a1.shape #dimension

array([0, 1, 2, 3, 4])

(5,)

#### For an 2D array a.shape displays: number of dimensions = rows, and number of columns: (rows,columns)

In [10]:
display.display(a3)
a3.shape #dimension

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

(2, 4)

### Playing with dimensions

In [11]:
a1D = np.array([1,2,3]) #One vector type
a2D = np.array([[1,2,3]]) #Matrix type
display.display(a1D.shape)
display.display(a2D.shape)

#Compare arrays
np.array_equal(a1D,a2D)  

(3,)

(1, 3)

False

### Reshape Dimension

In [12]:
a1D.shape[0]

3

In [13]:
new_dim = (1,a1D.shape[0])
a = a1D.reshape(new_dim)
a, a.shape

(array([[1, 2, 3]]), (1, 3))

In [14]:
np.array_equal(a,a2D)

True

### Access Elements within an Array : Slicing

In [15]:
a = np.array([[1,0,3],
              [4,3,5],
              [6,10,-1]])
a

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [16]:
a[1,2], a[0,0], a[2,2], a[2,1] #index starts in 0: [row, column]

(5, 1, -1, 10)

In [18]:
a = np.arange(10)
b = np.eye(5) #Only diagonal matrix with ones
display.display(a); display.display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
a[:5]

array([0, 1, 2, 3, 4])

In [20]:
b[:,2] #array[columns,rows]

array([0., 0., 1., 0., 0.])

In [21]:
b[:,1], b[2,:]

(array([0., 1., 0., 0., 0.]), array([0., 0., 1., 0., 0.]))

In [22]:
b[:,:]

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##  Math Operations

In [23]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [24]:
print(f'a={a}\n',
      f'a+5 ={a+5}\n',
      f'a-5 ={a-5}\n',
      f'a*5 ={a*5}\n',
      f'a/2 ={a/2}\n',
      f'a//2 ={a//2}\n',
      f'a**2 ={a**2}\n',
      f'a%(mod) 2 = {a%2}\n',
      f'-a = {-a}'
     )

a=[0 1 2 3]
 a+5 =[5 6 7 8]
 a-5 =[-5 -4 -3 -2]
 a*5 =[ 0  5 10 15]
 a/2 =[0.  0.5 1.  1.5]
 a//2 =[0 0 1 1]
 a**2 =[0 1 4 9]
 a%(mod) 2 = [0 1 0 1]
 -a = [ 0 -1 -2 -3]


###  Functions

In [25]:
a = np.arange(4)
b = np.arange(1,5)
c = np.arange(4,10)
a , b , c

(array([0, 1, 2, 3]), array([1, 2, 3, 4]), array([4, 5, 6, 7, 8, 9]))

In [26]:
display.display(np.exp(a))
display.display(np.log(b))
display.display(np.sqrt(a))
#compare element by element:
display.display(np.greater(a,b)) # a>b
display.display(np.greater(b,a))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

array([ True,  True,  True,  True])

### Statistics and Randomness

In [27]:
a = np.arange(10)

display.display(np.mean(a))
display.display(np.median(a))

4.5

4.5

In [29]:
#Random numbers
r = np.random.random(10)

In [30]:
display.display(np.mean(r))
display.display(np.median(r))

0.4191575554012785

0.35615745107085384